# TTSizer Pipeline Configuration v1.1

# ----------------------------------------------------------------------
#                  Core Project Setup (User Inputs)
# ----------------------------------------------------------------------
project_setup:
  project_name: "MyAnimeProject"
  video_source_parent_dir: "/home/taresh/Downloads/anime/videos"
  output_base_dir: "/home/taresh/Downloads/anime/audios_processed"
  target_speaker_labels_for_diarization: ["Momo Ayase", "Ken Takakura"]


# ----------------------------------------------------------------------
#                     Pipeline Control
# ----------------------------------------------------------------------
pipeline_control:
  run_only_stage: null
  start_stage: null
  end_stage: null

# ----------------------------------------------------------------------
#                Stage-Specific Configurations
# Output paths for stages are now relative to:
#   {project_setup.output_base_dir}/{project_setup.project_name}/
# ----------------------------------------------------------------------

# 1. Audio Extraction from Video
extract_audio_config:
  output_stage_folder_name: "01_extracted_audio"
  preferred_lang_codes: ["eng", "en", "english"]
  max_workers: 6
  output_sample_rate: 44100
  output_codec: "flac"
  resolution_threshold_for_aac_step: 480
  intermediate_aac_bitrate: "40k"

# 2. Vocal Removal
vocal_removal_config:
  output_stage_folder_name: "02_vocals_removed"
  model_type: "mel_band_roformer"
  use_gpu: true
  gpu_ids: [0]
  output_format: "flac"
  output_pcm_type: "PCM_24"
  skip_if_output_exists: true
  model_path: "weights/kimmel_unwa_ft2_bleedless.ckpt"
  model_config_path: "configs/config_kimmel_unwa_ft.yaml"

# 3. Audio Normalization (for vocals)
normalize_audio_config:
  output_stage_folder_name: "03_vocals_normalized"
  target_lufs: -20.0
  target_tp: -1.5
  sample_rate: 44100
  output_codec: "flac"
  num_processes: 6
  ffmpeg_timeout_seconds: 600
  skip_if_output_exists: true

# 4. LLM Diarization & Initial Transcription
llm_diarizer_config:
  output_stage_folder_name: "04_llm_diarized_json"
  model_name: "gemini-1.5-flash-latest"
  temperature: 0.1
  top_p: 0.8
  prompt_template_file: "prompt_template.txt"
  skip_if_output_exists: true

# 5. CTC Forced Alignment
ctc_forced_aligner_config:
  output_stage_folder_name: "05_aligned_clips"
  language_code: "en"
  batch_size: 8
  use_gpu: true
  init_start_pad_seconds: 0.4
  init_end_pad_seconds: 0.7
  min_words_per_segment: 2
  min_duration_seconds_segment: 0.5
  skip_episode_patterns: []
  output_audio_format: "wav"
  output_audio_subtype: "PCM_24"
  skip_if_output_exists: true
  model_name_or_path: "MahmoudAshraf/mms-300m-1130-forced-aligner"

# 6. Find Outliers
find_outliers_config:
  output_stage_folder_name: "06_outliers_filtered"
  input_stage_folder_name: "05_aligned_clips"
  project_audio_sources:
    - input_subpath_relative_to_input_stage: "Momo_Ayase_aligned"
      target_speaker_label: "Momo Ayase"

  audio_file_format_glob: "*.wav"
  target_sample_rate: 16000
  use_gpu: true
  min_clip_duration_seconds: 0.75
  centroid_refinement_percentile: 50
  min_segments_for_refinement: 10
  min_segments_for_master_profile: 10
  outlier_threshold_definite: 0.70
  outlier_threshold_uncertain: 0.60
  move_uncertain_files: true
  uncertain_folder_name: "uncertain_clips"
  max_outlier_percentage_warn: 40.0
  skip_episode_patterns: []
  speaker_embedding_model_dir: "weights/wespeaker-voxceleb-resnet293-LM"


# 7. Parakeet ASR Transcription
parakeet_asr_config:
  output_stage_folder_name: "07_parakeet_transcribed"
  batch_size: 4
  device: "cuda"
  timestamp_deviation_threshold_sec: 0.4
  padding_sec: 0.1
  audio_file_format_glob: "*.wav"
  model_name: "nvidia/parakeet-tdt-0.6b-v2"
  output_subfolder_names:
    flagged_cropped: "flagged_for_review_cropped"
    processed_main: "processed_main_dataset"

# Logging configuration
logging_config:
  log_level: "INFO"
  log_dir: "logs"
  log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  log_file_prefix: "ttsizer"